version: '3.3'

services:
    php-fpm:
        command: php-fpm8.1
        env_file:
            -   .env
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        build:
            dockerfile: Dockerfile
            context: .
            target: development
        volumes:
            - ./:/var/www